Add metadata in Chart.yaml
I'm trying to incorporate this Helm chart into a custom Helm charts repo, so I can use this as a Rancher catalog. The  helm/chart-releaser-action Github Action however is complaining about missing metadata:

```
Error: validation: chart.metadata is required
Run helm/chart-releaser-action@v1.0.0-rc.2
Installing chart-releaser...
Packaging chart 'charts/bitwarden_rs'...
Error: validation: chart.metadata is required
```